######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 5 13:21:12 2009
######################################################################
include(../../npr_header.pri)

QT += xml

TEMPLATE = app
TARGET = 
DEPENDPATH += ../include 
INCLUDEPATH += ../include 

PRE_TARGETDEPS += ../lib.$${DBGNAME}/libcda.a
LIBS += -L../lib.$${DBGNAME} -lcda

# Input
SOURCES += cdastats.cc
